### ISSUE TITLE
Support for batched inference?

### ISSUE THREAD

**Issue by ksrinivs64** [uiuc-focal-lab/syncode#124]
Hi, thanks for a very nice library.  Do you support batched inference?  Thanks

**Comment by shubhamugare** [comment]
Yes, it supports batched inference

**Comment by ksrinivs64** [comment]
Can you point to how? The examples seem to show a single prompt and there
seems to be a call to reset for each prompt. Thanks again.

**Comment by ksrinivs64** [comment]
To clarify,  the reset for each prompt seems to happen in the code to generate per prompt.

**Comment by shubhamugare** [comment]
You can run something like following for batched inference:

```
syn_llm = Syncode(model=model_name, grammar='json', parse_output_only=True, max_new_tokens=50, num_return_sequences=5, do_sample=True, temperature=0.7)

prompt = "Please return a json object to represent country India with name, capital and population?"
output = syn_llm.infer(prompt)

for i, out in enumerate(output):
    out = out.strip()
    print(f"SynCode output {i+1}:\n{out}\n")
    
 ```
