### ISSUE TITLE
how to pipinstall it？

### ISSUE THREAD

**Issue by jjjxusbx** [uiuc-focal-lab/syncode#54]
![屏幕截图 2024-03-24 181249](https://github.com/uiuc-focal-lab/syncode/assets/146902099/c8f56fef-b6e2-42f9-ace5-a23087cea33b)

**Comment by shubhamugare** [comment]
Can you refer to this https://stackoverflow.com/questions/22041752/github-clone-succeeded-but-checkout-failed. It seems like the issue is specific to windows and there are a few possible solutions discussed on stackiverflow.
