### ISSUE TITLE
Regarding the problem of converting regular expressions into FSM

### ISSUE THREAD

**Issue by GengYage** [uiuc-focal-lab/syncode#64]
In python.lark, how do you handle the error when converting regular expressions containing lookbacks/lookaheads into fsm?

**Comment by shubhamugare** [comment]
Hi,

I replaced those regular expressions with simpler regular expressions that avoid lookbacks/lookaheads. To maintain soundness of the approach you only need each regular expression to overapproximate the exact set of possible values certain terminals can take.
