### ISSUE TITLE
Option to add huggingface token for gated models?

### ISSUE THREAD

**Issue by border-b** [uiuc-focal-lab/syncode#79]
Currently we can not use models with gated repos from huggingface since they need authentication. 
Is there a way to pass the huggingface token to access the gated repos from huggingface?

**Comment by border-b** [comment]
Noticed the token is actually retrieved with `os.environ['HF_ACCESS_TOKEN']`. So I guess that should work. But I guess it would still be nice to have an option to add the token as an optional argument. Closing the issue.

**Comment by shubhamugare** [comment]
Hi @border-b,

Yes, the environment variable `HF_ACCESS_TOKEN` can be used to get under the gated model.

You can also consider importing SynCode logit processor and then can use all HF transformers API as in this [notebook](https://github.com/uiuc-focal-lab/syncode/blob/main/notebooks/example_logits_processor.ipynb). We haven't added README for that but the notebook example should be clear enough.
